Repository pingcap-incubator/tidb-in-action, pull requests merged in 2020-03, with the labels that each got.

#87 Add 5.2.8 Contribution Map
  res/session5/chapter2/contribution-map/1.png
  res/session5/chapter2/contribution-map/2.png
  res/session5/chapter2/contribution-map/3.png
  session5/chapter2/contribution-map.md
Labels: LGT1

#88 添加第三部分2.2分析 SQL 执行性能
  .gitignore
  res/session3/chapter3/slow-query-table/1.jpg
  res/session3/chapter3/slow-query-table/2.jpg
  session3/chapter3/slow-query-table.md
  session3/chapter3/statements.md
Labels: LGT1

#105 Add session5 chapter2-talent plan
  media/session5-chapter3-talent-plan-framework.png
  media/session5-chapter3-talent-plan-milestones.png
  media/session5-chapter3-talent-plan-students.png
  session5/chapter2/talent-plan.md
Labels: LGT1

#149 s1/c3.1: tidb-kv-to-relation.md
  session1/chapter3/tidb-kv-to-relation.md
Labels: LGT1

#140 Session3-Chapter1-SQL-Plan Part
  session3/chapter1/sql-plan.md
Labels: LGT1

#75 update tidb-sql-layer-summary.md
  SUMMARY.md
  session1/chapter3/tidb-sql-layer-summary.md
Labels: LGT1

#82 Add migration case about mongodb2tidb
  res/session4/chapter5/from-mongodb-to-tidb/1.png
  res/session4/chapter5/from-mongodb-to-tidb/10.png
  res/session4/chapter5/from-mongodb-to-tidb/2.png
  res/session4/chapter5/from-mongodb-to-tidb/3.png
  res/session4/chapter5/from-mongodb-to-tidb/4.png
  res/session4/chapter5/from-mongodb-to-tidb/5.png
  res/session4/chapter5/from-mongodb-to-tidb/6.png
  res/session4/chapter5/from-mongodb-to-tidb/7.png
  res/session4/chapter5/from-mongodb-to-tidb/8.png
  res/session4/chapter5/from-mongodb-to-tidb/9.png
  session4/chapter5/from-mongodb-to-tidb.md
Labels: LGT1

#170 s3/c1.3 sql-plan-management.md
  session3/chapter1/sql-plan-management.md
Labels: LGT1

#172 s3/c1 optimization-guide.md
  session3/chapter1/optimization-guide.md
Labels: LGT1

#166 add mysql-compatibility
  session1/chapter5/mysql-compatibility.md
Labels: LGT1

#112 tools: add intro
  .github/workflows/main.yml
  session5/chapter1/ecosystem-tools-community.md
  session5/chapter1/tidb-open-source-ecosystem.md
Labels: LGT1

#165 3.3.4: add metric summary doc
  session3/chapter3/metrics-summary.md
Labels: LGT1

#174 Update SUMMARY.md
  SUMMARY.md
Labels: LGT1

#180 add memory-quota-execution-time-limit.md
  session3/chapter1/memory-quota-execution-time-limit.md
Labels: Execution, LGT1

#182 *: add session5 chapter2 tidb user group
  SUMMARY.md
  res/session5/chapter2/events/tug.jpg
  session5/chapter2/tidb-user-group.md
Labels: Community, LGT1

#178 session5/chapter2: add pingcap university
  media/session5-chapter3-talent-plan-framework.png
  res/session5/chapter2/pingcap-university/tidb-dba-certified-program-milestones.png
  res/session5/chapter2/pingcap-university/tidb-dba-courses-framework.png
  res/session5/chapter2/pingcap-university/tidb-dba-students.png
  res/session5/chapter2/talent-plan/talent-plan-framework.jpg
  res/session5/chapter2/talent-plan/talent-plan-milestones.png
  res/session5/chapter2/talent-plan/talent-plan-students.png
  session5/chapter2/pingcap-university.md
  session5/chapter2/talent-plan.md
Labels: Community, LGT1

#187 session2: add content to session2/chapter1.3.2
  session2/chapter1/tidb-operator-scale.md
Labels: tidb-operator

#162 add session2-chapter2-cdc-internal and session2-chapter2-cdc-in-action
  res/session2/chapter2/cdc-in-action/1.png
  res/session2/chapter2/cdc-internal/1.png
  session2/chapter2/cdc-in-action.md
  session2/chapter2/cdc-internal.md
Labels: tools

#164 Update 2.1.1 CDC 解决什么问题 why-cdc.md
  session2/chapter2/why-cdc.md
Labels: tools

#159 Add TPCC
  session4/chapter3/tpc-c.md
Labels: LGT1

#188 update session2/chapter2 br related document
  session2/chapter2/br-internal.md
  session2/chapter2/br.md
Labels: tools/br

#186 s3/c1.4 parameter-tuning.md
  session3/chapter1/parameter-tuning.md
Labels: LGT1

#181 update tidb-in-enterprise-practices.md
  session4/chapter6/tidb-in-enterprise-practices.md
Labels: Best-Practices, LGT1

#175 SUMMARY.md: claim of seesion 4 chapter 6.2 sql_optimization_case
  res/session4/chapter6/sql_optimization_case/case4_coprocessor2.png
  res/session4/chapter6/sql_optimization_case/case4_duration.png
  res/session4/chapter6/sql_optimization_case/case4_hot.png
  res/session4/chapter6/sql_optimization_case/case4_p95handle_duration.png
  res/session4/chapter6/sql_optimization_case/case4_pi5.png
  res/session4/chapter6/sql_optimization_case/case4_pic1.png
  res/session4/chapter6/sql_optimization_case/case4_pic10.png
  res/session4/chapter6/sql_optimization_case/case4_pic12.png
  res/session4/chapter6/sql_optimization_case/case4_pic13.png
  res/session4/chapter6/sql_optimization_case/case4_pic2.png
  res/session4/chapter6/sql_optimization_case/case4_pic3.png
  res/session4/chapter6/sql_optimization_case/case4_pic6.png
  res/session4/chapter6/sql_optimization_case/case4_pic7.png
  res/session4/chapter6/sql_optimization_case/case4_pic8.png
  res/session4/chapter6/sql_optimization_case/case4_pic9.png
  res/session4/chapter6/sql_optimization_case/case4_pic_coprosessor.png
  res/session4/chapter6/sql_optimization_case/case4_region_splict.png
  session4/chapter6/sql-optimization-cases.md
Labels: SQL-Optimization-Cases

#90 session2_chapter2_dumpling-internal初稿
  res/session2/chapter2/dumpling/1.png
  session2/chapter2/dumpling-internal.md
Labels: LGT1

#179 Update optimizer-summary.md
  session3/chapter1/optimizer-summary.md
Labels: LGT1, Optimizer

#183 session3/chapter3/cluster-info-tables.md&metrics-schema.md&inspection-tables.md
  session3/chapter3/cluster-info-tables.md
  session3/chapter3/inspection-tables.md
  session3/chapter3/metrics-schema.md
  session3/chapter3/slow-query-table.md
Labels: infomation-schema

#204 add cloud, test, deployment, docs projects intro
  session5/chapter1/tidb-open-source-ecosystem.md
Labels: Community, LGT1

#115 1.2.1 tidb-operator-intro
  session2/chapter1/tidb-operator-intro.md
Labels: tidb-operator

#177 add two files:
  session2/chapter1/tidb-operator-deployment-private-delete.md
  session2/chapter1/tidb-operator-deployment-private-node.md
Labels: tidb-operator

#132 session2_chapter2_dumpling-intro初稿
  session2/chapter2/dumpling-intro.md
Labels: LGT1, tools

#197 Update two-dc-binlog.md
  session4/chapter4/two-dc-binlog.md
Labels: multi-dc

#203 update session1\chapter6\pessimistic-txn.md
  res/session1/chapter6/pessimistic-txn/1.png
  res/session1/chapter6/pessimistic-txn/2.png
  session1/chapter6/pessimistic-txn.md
Labels: transaction

#104 finished 1.2.7 1.2.8
  session2/chapter1/tidb-operator-tools.md
  session2/chapter1/tidb-operator-upgrade.md
Labels: tidb-operator

#176 7.1 表结构设计最佳实践 文章提交
  res/session1/chapter7/tidb-schema-design/tidb-data-overview.png
  res/session1/chapter7/tidb-schema-design/tidb-split-region.png
  session1/chapter7/tidb-schema-design.md
Labels: ddl

#219 session1/chapter4: add scheduling overview
  SUMMARY.md
  session1/chapter4/scheduling-overview.md
Labels: LGT1

#201 1.2.6 Tidb-operator-lightning
  session2/chapter1/tidb-operator-lightning.md
Labels: tidb-operator

#234 add doc for tidb access and monitoring
  session2/chapter1/tidb-operator-access-monitoring.md
Labels: tidb-operator

#245 update tidb open source ecosystem
  session5/chapter1/tidb-open-source-ecosystem.md
Labels: Community, LGT1
